version: '3.4'
services:
  ocelotapigateways:
    image: ${DOCKER_REGISTRY-}ocelotapigateways
    build:
      context: .
      dockerfile: OcelotApiGateways/Dockerfile
    ports:
     - "8111:80"
     - "8222:443"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_Kestrel__Certificates__Default__Password=ASPNETCORE_ENVIRONMENT
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
